#!/usr/bin/env python3

import argparse
import string
import subprocess

IMAGE = 'astro'
NOTEBOOK = 'astro-notebook'
# >>> IPython.lib.passwd("astro")
NOTEBOOK_PASSWORD = \
    'sha1:a148b9fcf1b4:fa83f953fbd59df90711b90119d8ab214fccff18'


def sh(cmd, **args):
    code = subprocess.call(
        string.Template(cmd).substitute(**args),
        shell=True)
    if code:
        exit(code)


def build():
    sh('docker build --rm -t ${IMAGE} .',
       IMAGE=IMAGE)


def run(command):
    sh('docker run --rm -it -v `pwd`:/work -w /work'
       ' ${IMAGE} ${COMMAND}',
       IMAGE=IMAGE,
       COMMAND=' '.join(command))


def test():
    run(['pytest astro.py'])
    run(['flake8'])


def notebook():
    sh('docker rm -f ${NOTEBOOK} || true',
       NOTEBOOK=NOTEBOOK)
    sh('docker run -d --name ${NOTEBOOK} -v `pwd`:/work -w /work -p 8888:8888'
       ' ${IMAGE} bash -c "'
       'jupyter notebook'
       ' --allow-root --NotebookApp.password=${NOTEBOOK_PASSWORD} --ip=\'*\''
       '"',
       NOTEBOOK=NOTEBOOK,
       IMAGE=IMAGE,
       NOTEBOOK_PASSWORD=NOTEBOOK_PASSWORD)


parser = argparse.ArgumentParser(
    description='Runner script for Astro'
)
parser.set_defaults(action=lambda: parser.print_help())
subs = parser.add_subparsers()

subs.add_parser('build').set_defaults(action=build)

p = subs.add_parser('run')
p.add_argument('command', nargs='*', default=[])
p.set_defaults(action=run)

subs.add_parser('test').set_defaults(action=test)

subs.add_parser('notebook').set_defaults(action=notebook)

args = vars(parser.parse_args())
action = args.pop('action')
action(**args)
